FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

RUN uv pip install --system mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
    "--backend-store-uri", "sqlite:///mlflow.db", \
    "--host", "0.0.0.0", "--port", "5000", \
    "--allowed-hosts", "localhost:*,mlflow-server:*"]
